### ISSUE TITLE
Help do me a big favor

### ISSUE THREAD

**Issue by abdulbadii** [joergoster/Moonfish#3]
As we see more and more coders enthusiastically beef up a better chess engine..
I'd ask you a favor to create a repo and put quite strong engine Ethereal in C (by Andrew G) which 's been being converted to C++ almost 1/3 of it

https://github.com/abdulbadii/Ethereal_CPP/tree/master/src

along with the all your repos in order to be improved by more c++ coder and gets the most blessed one.
I'm deleting this repo as soon as you grant it and do so.

**Comment by joergoster** [comment]
@abdulbadii Is there a problem with your repository? I would recommend to better ask for help in a forum, for example http://talkchess.com/forum3/index.php or http://outskirts.altervista.org/forum/index.php.

I also see no need to port Ethereal code into C++. Andrew Grant wrote very clean and comprehensible code, imho.

And since this is in no way related to my Moonfish project, I will close this one.
